name: Link Check

on: [push]

jobs:
  linkcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Check links with linkcheck
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: https://www.mirhamasala.com/posts/the-fear-list --external --skip-file /skip-file.txt

      - name: Save linkcheck results
        run: echo "${{ steps.linkcheck.outputs.stdout }}" > linkcheck-results.txt

      - name: Upload linkcheck-results.txt as artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: linkcheck-results
          path: linkcheck-results.txt
