name: Link Check

on: [push]

jobs:
  linkcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Check links with linkcheck
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: https://www.mirhamasala.com/posts/the-fear-list --external --skip-file skip-file.txt > linkcheck-results.txt
        id: linkcheck
        continue-on-error: true

      - name: Upload linkcheck-results.txt as artifact
        uses: actions/upload-artifact@v2
        with:
          name: linkcheck-results.txt
          path: linkcheck-results.txt
