name: Link Check

on: [push]

jobs:
  linkcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Check Dart Availability
        run: dart --version || echo "Dart is not installed"

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@main

      - name: Install linkcheck
        run: dart pub global activate linkcheck

      - name: Check gh CLI Availability
        run: gh --version || echo "gh CLI is not installed"

      - name: Run linkcheck
        run: dart pub global run linkcheck:linkcheck https://www.mirhamasala.com/posts/the-fear-list --external > linkcheck-results.txt
        continue-on-error: true

      - name: Upload linkcheck-results.txt as artifact
        uses: actions/upload-artifact@v2
        with:
          name: linkcheck-results
          path: linkcheck-results.txt
