name: Link Check

on: [push]

jobs:
  linkcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Check links with linkcheck
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: https://www.mirhamasala.com/posts/the-fear-list --external --skip-file linkcheck-skip-file.txt > linkcheck-results.txt
        id: linkcheck

      - name: Debug Linkcheck Exit Code
            run: echo "Linkcheck Exit Code: ${{ steps.linkcheck.outputs.exitcode }}"

      - name: Upload linkcheck-results.txt as artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: linkcheck-results
          path: linkcheck-results.txt

      - name: Create Issue on Faled workflow
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Action workflow failed.
          body: |
            ### Context
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
            Workflow name - `${{ github.workflow }}`
            Job -           `${{ github.job }}`
            status -        `${{ job.status }}`
