name: Broken Link Check

on:
  push:

jobs:
  build-and-check:
    name: Build Hugo and Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build Hugo Site
        run: hugo --
