name: Link Check

on: [push]

jobs:
  linkcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Check links with linkcheck
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: https://www.mirhamasala.com/posts/the-fear-list --external --skip-file skip-file.txt > linkcheck-results.txt
        id: linkcheck
        continue-on-error: true

      - name: Upload linkcheck-results.txt as artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: linkcheck-results
          path: linkcheck-results.txt

      - name: Create Issue
        uses: actions/github-script@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = "My Issue Title";
            const issueBody = "This is the issue body.";
            const octokit = new github.GitHub(token);

            octokit.issues.create({
              owner: github.repository_owner,
              repo: github.repository,
              title: issueTitle,
              body: issueBody,
            });
      # - name: Open a GitHub issue
      #   uses: octokit/request-action@v2.1.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     route: POST /repos/${{ github.repository }}/issues
      #     body: |
      #       {
      #         "title": "Broken links found in documentation",
      #         "body": "The link check workflow found broken links. Please review and fix them.",
      #         "labels": ["bug"]
      #       }
