name: Broken Link Check

on:
  push:

jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build Hugo site
        run: hugo

      - name: Check links with linkcheck
        uses: filiph/linkcheck@2.0.23
